### ISSUE TITLE
Add toggle in plugins menu (or any other easy way of toggling on/off)

### ISSUE THREAD

**Issue by XertroV** [sylae/DiegeticInfoDisplay#3]

**Comment by sylae** [comment]
This is actually mostly already done (ref: 3afd8a5be1938d20525e5c22c33a21a0f9866fc9) and will be out in the next version

A menu option isn't a bad idea tho instead of having to go into the settings window

**Comment by sylae** [comment]
implemented in commit 3819b25b592201c437cfbf5129e5727b38f79e01
