### ISSUE TITLE
Add cheap stroke: draw black bg with larger stroke size

### ISSUE THREAD

**Issue by XertroV** [sylae/DiegeticInfoDisplay#4]
Easier than for text (which needs to be replicated ~30 times to look good).

**Comment by sylae** [comment]
added a stroke option for now, but it's expensive (just drawing the text twice). A more optimized version would be pretty cool but I think I'll wait on a less garbage font pipeline for now (actual text support would be fantastic, barring that I want to see how far i can get with beziers (re: #5))

**Comment by sylae** [comment]
Closing this as with the latest renderer optimizations stroking is pretty performant
