### ISSUE TITLE
Optimization: encode fonts using formats compatible with `ArcTo` or `BezierTo` (should be ~10x fewer drawing operations)

### ISSUE THREAD

**Issue by XertroV** [sylae/DiegeticInfoDisplay#5]
* https://openplanet.dev/docs/api/nvg/ArcTo
* https://openplanet.dev/docs/api/nvg/BezierTo

**Comment by XertroV** [comment]
Happy to look at some possible optimizations in my spare time, if it's welcome.

**Comment by sylae** [comment]
I actually looked into this, the issue I had was no support for 3d space transforms so it didn't look right.

If/when openplanet gets support for that, I'd love to get this implemented. In the meantime if you have other optimization ideas I'd love to hear them!

**Comment by XertroV** [comment]
Ahh, yeah good point.

I *think* mb that beziers could be transformed to work, but not arcs. I don't know enough abot beziers yet, tho.

**Comment by XertroV** [comment]
hmm, maybe not -- from wiki page on beziers: seems like converting it to something else first makes things easy on the 3d side, but might be expensive on the cpu side.
![image](https://user-images.githubusercontent.com/1046448/213949951-806dc316-ecab-4733-8bb1-6b411231d4b8.png)

**Comment by sylae** [comment]
i'll have to double-check this, but i see no reason why i cant just translate all the bezier coordinates to Camera space just like we're doing with lines. assuming of course they operate like svg beziers it should be ez, and everything i've seen about nvg suggests it's svg in a trenchcoat so
