### ISSUE TITLE
Optional dependency-only mode where MLHook and MLFeed are not required?

### ISSUE THREAD

**Issue by XertroV** [sylae/DiegeticInfoDisplay#6]
Right now, MLHook and MLFeed are only needed for the default info that DID displays (AFAIK). It might be nice if there's a dependency-only mode where these requirements aren't present. Another plugin could still use DID without them.

**Comment by sylae** [comment]
Not a bad idea! I actually want to redo a lot of lane selection stuff to make it less shit, and this'd be a good feature to go with that!

**Comment by sylae** [comment]
resolved in d2f9b83d1fd2daa0c5f376c2f7d685b783e5fef2
